### ISSUE TITLE
Why was the `unblock` function removed?

### ISSUE THREAD

**Issue by phil-opp** [smol-rs/blocking#12]
I just saw that the 0.5.0 version only has the `Unblock` type and the `unblock!` macro, but no longer the `unblock` function. Is there any reason for this apart from simplifying the API?

The reason I preferred the `unblock` function over the macro is that the `await` point is visible. Also, we can directly deduce from the function declaration (shown directly in the editior by rust-analyzer) that the function is asynchronous. With the `blocking!` macro, I have to read the documentation to understand that the passed argument doesn't really block even though it looks like that (e.g. `unblock!(fs::read(…))`).

**Comment by ghost** [comment]
It was removed because I thought the `unblock!` macro should be enough :) But that turned out to be a mistake.

Recently, after discussing this with folks in the Discord channel, we realized that actually all macros with hidden `await` inside are confusing and should be avoided. So I think I'll just remove the `unblock!` macro and replace it with the old `unblock()` function.

Also, I feel it's time to stop fiddling with the API so I may just publish 1.0 at this point.

**Comment by phil-opp** [comment]
Sounds great, thanks a lot for all your work!

**Comment by ghost** [comment]
The master branch now has `unblock()`.

**Comment by phil-opp** [comment]
Great, thanks a lot!

**Comment by ghost** [comment]
(I forgot to add, the `unblock()` method is now available in v0.5.1)
