### ISSUE TITLE
Export unblock_unchecked method public

### ISSUE THREAD

**Issue by ethe** [smol-rs/blocking#34]
In current, `unblock` requires closure must be `'static`, is it possible to add a unsafe method `unblock_unchecked` to remove this constraint, just like `async_task::spawn_unchecked`? It must be useful to let other user to make their own unblock wrapper.

**Comment by notgull** [comment]
Is this sound? The docs for [`spawn_unchecked`](https://docs.rs/async-task/latest/async_task/fn.spawn_unchecked.html) say:

> If `future` is not `'static`, borrowed variables must outlive its `Runnable`.

Since the Runnable is stored in a 'static structure, it's out of the control of the user... though I don't think there's a way for the Runnable to outlive the Task, and even if there is we could just make it part of the contract for the function.

Regardless, I'm hesitant to add new unsafe code to this crate.

**Comment by ethe** [comment]
I am building a wrapper of `blocking`, which supports "scoped-unblock" method like [scoped threads](https://doc.rust-lang.org/stable/std/thread/fn.scope.html). However, I think it is impossible if we do not have a method like `blocking::unblock_unchecked`. But the similar method "scoped-task" would be very easy to be built on `async_task::spawn_unchecked`. In scoped-task context, we could easy to provide a way that promises all captured variables outlive the task, and they are also not `'static`.

**Comment by notgull** [comment]
Yes, maybe scoped tasks would be a nice abstraction. I'll look into adding it to `async-task`, and then we might be able to also add it to `blocking`.

**Comment by notgull** [comment]
I'm going to close this for now. I'd like to avoid adding unsafe code, and the underlying problem here (scoped tasks) are very difficult to do correctly in the current Rust. Thanks anyhow!
